### ISSUE TITLE
Problem with expedition percentages

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#369] opened 2019-11-08 00:18 UTC
A couple of volunteers have commented on problems with the expedition percentages.
I'm not really sure what is happening but it is possibly something to do with the tasks locking ie they are not transcribed but they are not available to be transcribed as they are locked.

Diane Gershwin 6 Nov 2019 -     There are 2 active expeditions at the moment, one is 93% complete and the other 32% at the time of posting, but the percentages are showing up as zero on the home page.

**Comment by RhiannonStephens** [comment] 2019-11-08 00:27
5 Nov 2019 MM Debeer - Cases in Hobart against Women
I have lost at least 5 transcribed and submitted tasks from this expedition (and I am not the only one...)  Unlike in in other expeditions, it appears submitted (and saved) tasks can be opened from the transcriber's profile and be editable (then, presumably, submitted)  Would someone like to test this out with me and swap one transcription?

7 Nov 2019 MM Debeer - 'Cases in Hobart against women' expedition, the percent transcriptions jumped back, from almost complete to the mid eighty percent, at the same time as a reduction in the number of transcriptions completed per expeditioner? It was between the 1st & 5th NovemberI can only speak for noticing this in
mine:                     from 53 to late 40s
Ross Davidson:     from 40 transcriptions to mid 30s. (obviously, I trawl the competition...)

**Comment by cdausmus** [comment] 2020-10-01 01:13
After discussion with @RhiannonStephens, marking this as unable to reproduce.

**Closed** 2020-10-01 01:14 UTC
Labels: Type - bug
